name:                proofnumber
version:             0.1.0.0
github:              "davidspies/proofnumber"
license:             BSD3
author:              "David Spies"
maintainer:          "dnspies@gmail.com"
copyright:           "2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            games

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- ViewPatterns

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/davidspies/proofnumber#readme>

ghc-options: -Werror -Wall

dependencies:
- base >= 4.7 && < 5
- containers
- hashable
- MissingH
- memo-hashtables
- pcg-random
- pointless-fun
- singletons
- vector

library:
  source-dirs: src

executables:
  proofnumber-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proofnumber
    - monad-loops

tests:
  proofnumber-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proofnumber
